export const SET_SHOW_LOADING = 'SET_SHOW_LOADING';
export const SET_HIDE_LOADING = 'SET_HIDE_LOADING';
export const SET_TOGGLE_MENU = 'SET_TOGGLE_MENU';
export const SET_TOAST = 'SET_TOAST';
export const SET_MOBILE = 'SET_MOBILE';
export const SET_TOKEN = 'SET_TOKEN';

export const SET_TOGGLE_SIDEBAR = 'SET_TOGGLE_SIDEBAR';
